
version: '2'
services:
  web:
    image: gitlab/gitlab-ce:$GITLAB_VERSION
    hostname: $GITLAB_HOST
    environment:
      GITLAB_OMNIBUS_CONFIG: external_url 'https://$GITLAB_HOST'
    volumes:
    - $VOLUME_MOUNT_POINT/gitlab/config:/etc/gitlab
    - $VOLUME_MOUNT_POINT/gitlab/logs:/var/log/gitlab
    - $VOLUME_MOUNT_POINT/gitlab/data:/var/opt/gitlab
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 2222:22/tcp
    # NOTE: 22 would clash with the normal host ssh
