
version: '2'

secrets:
  GITLAB_DATABASE_HOST:
    external: true
  GITLAB_DATABASE_USERNAME:
    external: true
  GITLAB_DATABASE_PASSWORD:
    external: true
  GITLAB_SMTP_USER_PASSWORD:
    external: true
  GITLAB_BACKUP_SPACE_KEY:
    external: true
  GITLAB_BACKUP_SPACE_SECRET:
    external: true

services:

  redis:
    image: redis:4.0.9-alpine
    # command:
    #   - --loglevel warning

  web:
    # image: gitlab/gitlab-ce:$GITLAB_VERSION
    image: local/gitlab:wrapped
    labels:
      io.rancher.scheduler.affinity:host_label: service=gitlab
    hostname: $GITLAB_HOST
    secrets:
      - GITLAB_DATABASE_HOST
      - GITLAB_DATABASE_USERNAME
      - GITLAB_DATABASE_PASSWORD
      - GITLAB_SMTP_USER_PASSWORD
      - GITLAB_BACKUP_SPACE_KEY
      - GITLAB_BACKUP_SPACE_SECRET
    environment:
      GITLAB_HOST: $GITLAB_HOST
      # postgresql['enable'] = false
      GITLAB_OMNIBUS_CONFIG: external_url 'https://$GITLAB_HOST'
      ######################
      # all variables: http://j.mp/2tjKh3v
      # the sensitive ones are set in the docker entrypoint of the build
      GITLAB_DATABASE_ADAPTER: postgresql
      GITLAB_DATABASE_PORT: 5432
      GITLAB_DATABASE_ENCODING: utf8
      GITLAB_DATABASE_DATABASE: gitlabdb
      ######################
      REDIS_HOST: redis
      ######################
      # GITLAB_SMTP_DOMAIN: $GITLAB_SMTP_DOMAIN
      # GITLAB_SMTP_ADDRESS: $GITLAB_SMTP_ADDRESS
      # GITLAB_SMTP_PORT: 465 # SSL
      GMAIL_SMTP_DOMAIN: smtp.gmail.com
      GMAIL_SMTP_PORT: 587
      GITLAB_SMTP_USER_NAME: $GITLAB_SMTP_USER_NAME
      ######################
      GITLAB_EMAIL_FROM: $GITLAB_SMTP_USER_NAME
      GITLAB_EMAIL_REPLY_TO: $GITLAB_SMTP_USER_NAME
    volumes:
    - /mnt/$VOLUME_NAME/gitlab/config:/etc/gitlab
    - /mnt/$VOLUME_NAME/gitlab/logs:/var/log/gitlab
    - /mnt/$VOLUME_NAME/gitlab/data:/var/opt/gitlab
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 2222:22/tcp # NOTE: 22 would clash with the normal host ssh
  # ADD REDIS
